apiVersion: v1
kind: Service
metadata:
  name: proyectojenkins-service
spec:
  selector:
    app: proyectojenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer
